#!/usr/bin/env bash
# script to add redirect to nginx default
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginc/sites-available/default
sudo ufw allow 'Nginx HTTP'
service nginx start
