#!/usr/bin/env bash
# script to add redirect to nginx default
# add http header 
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404code.html
sed -i "/listen 80 default_server/a add_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404code.html;' /etc/nginx/sites-available/default
service nginx start
