#!/usr/bin/env bash
# setup scriptfor haproxy 2.0 on ubuntu server
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install -y haproxy=2.0
echo \
	"
frontend load_balancer
	bind *:80
	mode http
	default_backend web_servers

backend web_servers
	balance roundrobin
	mode http
	server 1345-web-01 35.185.2.47
	server 1345-web-02 3.94.190.44" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
