#!/usr/bin/env bash
# set localhost and facebook.com to custom ips
cp /etc/hosts tmphosts
sed -i s/^127.*/"127.0.0.2 localhost"/ tmphosts
echo "8.8.8.8 facebook.com" >> tmphosts
cp tmphosts /etc/hosts
